// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIRI1D0Zbv60XtsxXOGmIsEAyuWBSWOR0',
    appId: '1:582271404230:web:c9c0210496a242bf2eefc7',
    messagingSenderId: '582271404230',
    projectId: 'a1-project-d8576',
    authDomain: 'a1-project-d8576.firebaseapp.com',
    storageBucket: 'a1-project-d8576.appspot.com',
    measurementId: 'G-J0847928G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2TJa5LOdtfzKTP2aQ-ZAeaFChZrUC-bg',
    appId: '1:582271404230:android:6ae34731a9a3ddfa2eefc7',
    messagingSenderId: '582271404230',
    projectId: 'a1-project-d8576',
    storageBucket: 'a1-project-d8576.appspot.com',
  );
}
